import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compilePhoneData, type PhoneSource, type TimezoneSource } from './phone/compiler.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = resolve(root, 'docs/phone-numbering/source')

async function main() {
  const meta = JSON.parse(await readFile(resolve(source, 'meta.json'), 'utf8')) as {
    version: number; builtAt: string; files: { file: string; sha256: string }[]
  }
  if (meta.version !== 1) throw new Error(`Неизвестная версия базы телефонов: ${meta.version}`)
  async function readVerified<T>(file: string): Promise<T> {
    const bytes = await readFile(resolve(source, file))
    const expected = meta.files.find((entry) => entry.file === file)?.sha256
    if (createHash('sha256').update(bytes).digest('hex') !== expected) throw new Error(`${file}: контрольная сумма не совпадает с meta.json`)
    return JSON.parse(bytes.toString('utf8')) as T
  }
  const result = compilePhoneData(
    await readVerified<PhoneSource>('mobile.json'),
    await readVerified<{ slug: string; name: string }[]>('regions.json'),
    await readVerified<TimezoneSource>('timezones.json'),
  )
  const output = resolve(root, 'src/generated/phone-data.ts')
  const content = '// Generated by scripts/import-phone-data.ts. Do not edit. Sources: docs/phone-numbering/README.md\n' +
    "import type { PhoneRangeGroup } from '../data/phone-data'\n" +
    `export const phoneDataBuiltAt = ${JSON.stringify(meta.builtAt)}\n` +
    `export const phoneRangeGroups: readonly PhoneRangeGroup[] = [\n${result.groups.map((group) => JSON.stringify(group)).join(',\n')}\n]\n`
  await mkdir(dirname(output), { recursive: true })
  if (await readFile(output, 'utf8').catch(() => '') !== content) await writeFile(output, content, 'utf8')
  console.log(`Телефоны: ${result.groups.reduce((sum, group) => sum + group.ranges.length, 0)} диапазонов, ${result.groups.length} групп регионов; без региональной привязки исключено: ${result.excludedBlocks}. Снимок: ${meta.builtAt}.`)
}

main().catch((error: unknown) => {
  console.error('Не удалось подготовить базу телефонов:', error)
  process.exitCode = 1
})
